apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-typescript-deployment
spec:
  selector:
    matchLabels:
      app: server-typescript
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: server-typescript
    spec:
      containers:
        - env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URI
                  name: server-env
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: server-env
          image: vladimir44/crwn-server:0.1
          name: server
          ports:
            - containerPort: 8080
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
kind: Service
apiVersion: v1
metadata:
  name: server-typescript-service
spec:
  selector:
    app: server-typescript
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort
