kind: Service
apiVersion: v1
metadata:
  name: typescript-server-service
spec:
  selector:
    app: typescript-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort
